# your domain
domain: devildmc.top

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - https://github.com/yuzhi535/proxypool/edit/master/config/config.yaml
